[package]
name = "utilities"
version = "0.1.0"
authors = ["Parami Team <info@parami.io>"]
edition = "2018"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.102", optional = true }

# primitives
parami-node-primitives = { version = "3.0.0", path = "../../primitives", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
rstd = { package = "sp-std", default-features = false }
sp-runtime = { version = "2.0.0-alpha.2",default-features = false }
sp-io = { version = "3.0.0", default-features = false }

# frame dependencies
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "2.0.0-alpha.2", default-features = false }

[dev-dependencies]


[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
]
